name: CI/CD for react Todo 

on:
  push:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: self-hosted
    steps:
      - name: Build Project
        run: |
          hostname
         
