name: CI/CD for react Todo 

on:
  push:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        run: |
          hostname
      - name: checkout codigo
        uses: actions/checkout@v4
        
      - name: instala terraform
        uses: hashicorp/setup-terraform@v3

        
     
          
         
